nome=input("Insira nome: ")
idade=int(input("Insira idade: "))
salario=float(input("Insira salario: "))
sexo=input("Sexo: F ou M? ")
estado_civil=input("Insira seu estado civil (S, C, V ou D): ")
sexo=sexo.upper()
estado_civil=estado_civil.upper()
print(estado_civil, sexo)
while (len(nome) < 3) or (idade < 0 or idade > 150) or salario < 0 or (sexo != 'F' and sexo != 'M') or (estado_civil != 'S' and estado_civil != 'C' and estado_civil != 'V' and estado_civil != 'D'):
    print("Informações inválidas, repita o procedimento!")
    nome=input("Insira nome: ")
    idade=input("Insira idade: ")
    salario=input("Insira salario: ")
    sexo=input("Sexo: F ou M? ")
    estado_civil=input("Insira seu estado civil (S, C, V ou D): ")